[git]
tmpRepository = "." # 用于抓取 git 分支列表的仓库
apply = [
    ["git", "add", "-A"],
    ["git", "commit", "-m", "apply"],
    ["git", "push"]
]

[project]
teams = ["team1", "team2", "team3", "team4", "team9"]
pattern = ["product", "client-product", "server-product", "gm-product"]

root = "."
config = "cfg.js"
flag =  "// 这是插入标记"

[workspace]
root = "."
log = "log" # 日志目录