name: go build

on: [push]

jobs:
  build_go:
    name: build go
    runs-on: macos-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: set up env
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: build
        run: go build

      - name: archive production artifact
        uses: actions/upload-artifact@v2
        with:
          retention-days: 5   # 保存时间
          name: lgc-${{ runner.os }}-v0.1.${{ github.run_number }}
          path: lgc

